package phraseapp

import phraseapp.internal.Platform
import phraseapp.network.*

open class PhraseappPluginExtension {
    /**
     * Project id of your PhraseApp project.
     */
    lateinit var projectId: String
    /**
     * Authentication token used to communicate with PhraseApp.
     */
    lateinit var authToken: String
    /**
     * Target location to print all translations from PhraseApp.
     */
    @Deprecated(
            message = "We are going to replace with resFolders property",
            replaceWith = ReplaceWith(
                    expression = "PhraseappPluginExtension.resFolders",
                    imports = ["phraseapp.PhraseappPluginExtension"]
            )
    )
    var resFolder: String = ""
    /**
     * Target locations to print all translations from PhraseApp.
     * If you use this property, the plugin will use strings.xml
     * file by default in the target resource folder.
     * If you have multiple strings files in one of your resource
     * folder, you can use `resFoldersMultiStrings` property.
     * @see resFoldersMultiStrings
     */
    var resFolders: List<String> = arrayListOf()
    /**
     * Target location to get print all translations from PhraseApp
     * and to fetch default strings files in all resource folders.
     */
    var resFoldersMultiStrings: Map<String, List<String>> = mapOf()
    /**
     * Generate the output adapted to the platform.
     */
    var platform: Platform = Platform.ANDROID
    /**
     * Download the default locale from PhraseApp and write it on the disk with the download task.
     * By default, we don't override the default file.
     */
    var overrideDefaultFile: Boolean = DEFAULT_OVERRIDE_DEFAULT_FILE
    /**
     * Phraseapp base url to consume Phraseapp API.
     * Optional parameter. Default value: https://api.phraseapp.com/api
     */
    var phraseappBaseUrl: String = PHRASEAPP_BASEURL
    /**
     * If you don't use the upload task, you don't need to fill this property.
     */
    var mainLocaleId: String? = null
    /**
     * If you aren't interested by the json file generated by the download task, you don't
     * need to fill this property.
     */
    var outputLocation: String? = null
    /**
     * If you want to convert a PhraseApp locale to your custom locale, add it into this map.
     * For example: ['zh-CN': 'zh-Hans']
     */
    var exceptions: Map<String, String> = DEFAULT_EXCEPTIONS
    /**
     * If you want to convert all placeholder into your platform's placeholder, switch this
     * parameter to true. Default: false.
     */
    var placeholder: Boolean = DEFAULT_PLACEHOLDER
    /**
     * If you want to specify your custom locale in the name of a PhraseApp locale, you can
     * specify the regex of your PhraseApp locale name here. Default: .+_([a-z]{2}-[A-Z]{2})
     */
    var localeNameRegex: String = DEFAULT_REGEX
}
